### ISSUE TITLE
add nvme support please

### ISSUE THREAD

**Issue by wangyugui** [doug-gilbert/ddpt#1]
Hi, 

Add nvme support please.

```
# ddpt --version
0.95 20141226 [svn: r307]

#ddpt oflag=pt,trim bs=64K if=a.img of=/dev/nvme0n1
INQUIRY failed on /dev/nvme0n1
```

nvme scsi command translation is droped. 
so we need some native nvme support.

Best Regards

**Comment by wangyugui** [comment]
There will be another option to used it with blkdiscard together?
step1) blkdiscard whole_block_device
step2) ddpt oflag=pt,sparse bs=64K; no trim command here, just skip this region?

blkdiscard of whole_block_device is better than a lot of small trim command?

**Comment by doug-gilbert** [comment]
It has been a while. I'm just finishing off the testing of a SNTL in the sg3_utils library which ddpt uses. There is some of the SNTL in ddpt release 0.96 My svn revision 378 should have a full working version. The ddpt command now supports --verify (as long as OFILE uses a pass-through).
    ddpt --verify if=/dev/sg3 of=/dev/nvme0n1 oflag=pt
ddpt will generate a SCSI VERIFY(BYTCHK=1) on /dev/nvme0n1 which the SNTL will transalte to the NVMe Compare command.

**Comment by wangyugui** [comment]
Now I'm using blkdiscard before dd.
so close this ticket.
